FROM mcr.microsoft.com/azure-storage/azurite:latest

LABEL maintainer="Saiyen Subban - ST10472464"
LABEL description="CoffeeNChill Azurite storage emulator for local Azure Functions development"
LABEL version="1.0"

EXPOSE 10000 10001 10002
